#menu:
#  Home: /
#  Archives: /archives


menu:
  - page: home
    directory: /
    icon: fa-home
  - page: archive
    directory: /archives
    icon: fa-archive

widgets:
# - search
- toc
- recent_posts
- category
- tag

excerpt_link: 阅读全文 #Continue Reading

comment:
  duoshuo: false
  duoshuo_short_name: mugbya
## to enable disqus, you need to fill in the disqus_shortname in config.yml
## to enable duoshuo, you need duoshuo id and set duosuo to true

#share plugins at the bottom of the article
share:
  enable: false
  jiathis: false ##a chinese sharing plugins for chinese users
  twitter: false
  google: false

bottom_link:
  google_plus: ##e.g. 104684175089936429154 for https://plus.google.com/u/0/104684175089936429154/posts
  github: mugbya
  twitter: ##e.g. ffff for https://twitter.com/ffff
  weibo: ##e.g. ffff for http://www.weibo.com/2316853071
  facebook: ##e.g. ffff for https://www.facebook.com/ffff
  renren: ##e.g. 333333333 for http://www.renren.com/333333333

logo:
  enable: true  ##display img
  src: img/favicon.ico ## 32 * 32px, logo img
  apple_icon: img/favicon.ico ## logo img for apple icon, 114 * 114 px

#your personal page, could be your github account page, twitter or google plus personal page
## By default its your homepage
personal_site:

fancybox: true

#you can change the custom font in head.ejs
CustomFont: true

#google analytics id, e.g.UA-28532742-2
google_analytics:

##url of your rss
##it is highly recommanded to use rss plugins, https://github.com/hexojs/hexo-generator-feed
rss: /atom.xml

#for Chinese users
ChineseUser: true
##默认false. 如果你的访客大部分来自中国, 那么请设置为true, cdn将会调换为360和百度公共库, 同时lang和content-language也会被修改
